/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.lalaalal.droni.server;

import com.lalaalal.droni.server.account.LoginRespondent;
import org.junit.Test;
import org.junit.experimental.categories.Category;

import java.io.PrintWriter;
import java.util.ArrayList;

import static org.junit.Assert.*;

@Category(LoginTest.class)
public class LoginTest {
    @Test public void testLogin() {
        try {
            ArrayList<String> data = new ArrayList<String>();
            data.add("test");
            data.add("098f6bcd4621d373cade4e832627b4f6");
            DroniRequest request = new DroniRequest("LOGIN", data);
            LoginRespondent loginRespondent = new LoginRespondent(new PrintWriter(System.out), request);

            boolean res = loginRespondent.login();
            assertTrue(res);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
